### ISSUE TITLE
Training Details

### ISSUE THREAD

**Issue by omega-cw** [nv-nguyen/cnos#1]
Hi, thanks for your nice work! 
And I have some questions hope you can help me:
1. during training of proposal stage, the usage of SAM(or Fast SAM) is promptable or not promptable. If promptable, which type of prompt do you use (point or bbox), and how do you get them? And if not promptable, how do deal with the over-segment problem.

**Comment by nv-nguyen** [comment]
To be clear, there is no training in our framework. During the onboarding and proposal stage, we use the pretrained model provided by SAM (or FastSAM) and DINOv2.

For SAM (or FastSAM), we use its [default not prompt setting](https://github.com/nv-nguyen/cnos/blob/main/configs/model/segmentor_model/sam.yaml#L2) by sampling 64 points per dimension. There is still a problem of over-segmentation but it can be filtered in the matching stage since their over-segmentation masks have lower confidence score comparing to correct segmentation masks. For example, we show in the teaser the segmentation on YCB-V dataset and most of the segmentation masks are filtered out.
