### ISSUE TITLE
Any standard for scaling CAD models?

### ISSUE THREAD

**Issue by saishruthibalaji** [nv-nguyen/cnos#10]
I have some custom CAD models which have dimensions originally in the order of 0.1m. However, they don't appear at all in the rendered images. So I scaled the mesh to 1000x using blender and then rendered. My rendered images are attached below: some of the regions are getting cut off. (This is mesh_001.ply in this [link](https://drive.google.com/drive/folders/1s9IcSc5q_yX0_EGxqQPoGT6doEo5hRaX?usp=drive_link)). Is there some standard in scaling the meshes so that I get perfect renders?

![templates](https://github.com/nv-nguyen/cnos/assets/106185420/47974d33-a600-402c-be23-95816b710820)

In turn, I'm also not getting any segmented results in the below test RGB Image:

![vis](https://github.com/nv-nguyen/cnos/assets/106185420/e0455e01-d263-4719-ab20-7d47dd48893c)

**Comment by nv-nguyen** [comment]
This issue has been fixed in the most recent commit with [this line](https://github.com/nv-nguyen/cnos/blob/main/src/poses/pyrender.py#L97). Here is what I get for the visualization of templates:

![templates](https://github.com/nv-nguyen/cnos/assets/54082176/8ac34066-cecb-4b5b-9b5c-eeb2fbc235c5)

Please note that you can also scale the mesh directly with our code by changing [this value `radius`](https://github.com/nv-nguyen/cnos/blob/main/src/scripts/render_custom.sh#L2) (distance to the camera) to bigger values, no need to use Blender.

I don't have your RGB image so I made a screenshot of the gray image above and run CNOS. Here is its result with the default hyper-parameters and `num_max_dets=20`. I think the results can be improved by changing the hyper-parameters and use your input RGB instead of gray image:

![vis](https://github.com/nv-nguyen/cnos/assets/54082176/aca6b96c-5d3b-4d77-8cb8-20f5ba615d84)

**Comment by saishruthibalaji** [comment]
Thank you! This was very helpful.
