### ISSUE TITLE
Problems with detecting multi-color objects (?)

### ISSUE THREAD

**Issue by jakob-ropers-snkeos** [nv-nguyen/cnos#11]
Hello once again! I return with another surgical tool that I am unable to segment. The original image and segmentation is shown below:
![vis_01](https://github.com/nv-nguyen/cnos/assets/114990727/0bab039c-870f-453c-baf1-3243d46d863c)

As you can see, absolutely nothing is detected. In order to make sure that it is not a problem with my CAD model, I masked out the entire tool to make it a single color. See below:
![vis](https://github.com/nv-nguyen/cnos/assets/114990727/49d36fb1-dfb8-403e-83d0-ce23c726c4d4)

With the same templates, it is suddenly detected. This brings me to the conclusion that it has something to do with the SAM segmentation. I ran the tool through SAM Segment Everything and found this:
<img width="1031" alt="SAM_Result" src="https://github.com/nv-nguyen/cnos/assets/114990727/2bfec15c-ac49-47cf-ac7f-12317619094f">

I believe the problem is that the tool has multiple colors and is segmented in a fragmented way instead of as an entire tool. Is there some way in this code to have an influence on connecting masks and checking them for a match?

**Comment by nv-nguyen** [comment]
As you mentioned, this issue is more related to SAM segmentation. Therefore, I suggest addressing it with the [SAM repo](https://github.com/facebookresearch/segment-anything) as they should provide you with better advice to resolve it than I can. In the meantime, if there are any questions or concerns regarding matching with CNOS that I can assist with, please feel free to open an issue here.
