### ISSUE TITLE
Segmentation evaluation using bop_toolkit

### ISSUE THREAD

**Issue by jrryzh** [nv-nguyen/cnos#16]
Thanks for the elegant code!
After i get the seg results using the command"python run_inference.py dataset_name=$DATASET_NAME model.onboarding_config.rendering_type=pyrender", i get the json file named"CustomSamAutomaticMaskGenerator_template_pyrender0_aggavg_5_lmo.json".

When i try to evaluate it using bop_toolkit, using scripts/eval_bop22_coco.py, bug occurs due to inappropriate name spliting.
I believe the cause is this:
```
  result_name = os.path.splitext(os.path.basename(result_filename))[0]
  result_info = result_name.split('_')
  method = str(result_info[0])
  dataset_info = result_info[1].split('-')
  dataset = str(dataset_info[0])
  split = str(dataset_info[1])
  split_type = str(dataset_info[2]) if len(dataset_info) > 2 else None
```

Can you check this and tell me how to fix this ? Thanks

**Comment by nv-nguyen** [comment]
I evaluated directly with BOP online evaluation and there is no issue. The issue that you are having here is from the name of prediction (I don't have this because the BOP online evaluation renames it directly). You can re-name the file with this format `f"{model_name}-pbrreal-rgb-mmodel_{dataset_name}-test_{run_id}"`

**Comment by jrryzh** [comment]
Thanks！
