### ISSUE TITLE
Running custom inference on multiple GPUs

### ISSUE THREAD

**Issue by Swaraj-72** [nv-nguyen/cnos#6]
Hello, thanks for the great work. While testing out the repo on my custom CAD model, I had memory issues and the requirement seems to be huge. I tried using CUDA_VISIBLE_DEVICES=0,1 before the bash command but it still uses 1 GPU only. Let me know what I might be doing wrong or a solution to this problem
![image](https://github.com/nv-nguyen/cnos/assets/65396498/03e26c0c-c2cb-47a9-8e69-707a6328a49a)

**Comment by nv-nguyen** [comment]
Yes, the current code for testing on custom objects do not support multi-gpus. If you want to do it, you can follow [run_inference.py](https://github.com/nv-nguyen/cnos/blob/main/run_inference.py#L26) and create a trainer to handle it.

However, using multi-gpus is not helpful in this case since your issue is from [this line](https://github.com/nv-nguyen/cnos/blob/main/src/scripts/inference_custom.py#L125). There are probably too much proposals for your testing images. Can you share your RGB images so that I can take a look?

**Comment by nv-nguyen** [comment]
Close the issue due to inactivity. Feel free to re-open it if you still have this problem!
