### ISSUE TITLE
Limited performance on Custom Datasets

### ISSUE THREAD

**Issue by jakob-ropers-snkeos** [nv-nguyen/cnos#9]
I tried this code and it works beautifully on the provided datasets. Considering the shots are cluttered with all kinds of objects, there are occlusions, etc. I am extremely impressed by the performance on this.
However, as soon as I move to a custom dataset, this performance is not repeatable whatsoever. I am trying this out on surgical tools, for which I have an accurate CAD model. The images I tried it on are close-ups of the objects, the single object only, a white background, and no occlusion; in other words, as simple as it gets and technically a perfect template match. However, the model either only predicts a tiny part of the object or just something completely wrong like the entire background (everything but the object).
Could you maybe comment on the types of objects this works well on (the objects in your datasets seem a bit more bulky while the surgical tools are more skinny) or whether there are any tricks to improving this performance?

**Comment by nv-nguyen** [comment]
From what you said “close-ups of the objects, the single object only, a white background, and no occlusion” but there is still no segmentation on objects are so weird since SAM or FastSAM should segment everything. You can reduce confidence_threshold to see all detections first and make sure that there are at least some masks on objects.

**Comment by jakob-ropers-snkeos** [comment]
Thank you for your very fast reply!

So here is an example where it worked best for me. As you can see, it still does not segment the entire object:
![Templates](https://github.com/nv-nguyen/cnos/assets/114990727/b558a784-52b4-4647-be70-cf1fd4a1fa2f)
![half_confidence](https://github.com/nv-nguyen/cnos/assets/114990727/9a684a0a-de81-4de4-8285-132122705898)

When I do it for another tool, I only get the background for some reason:
![template02](https://github.com/nv-nguyen/cnos/assets/114990727/59d1ad97-e281-4646-9a10-34a2499441fb)
![bad_results](https://github.com/nv-nguyen/cnos/assets/114990727/46b33c3e-7fd7-4eb6-b9d8-d5c9b17e6250)

I am confused because as soon as I use a CAD model and RGB image from one of the example datasets it segments it absolutely perfectly despite the object being far away from the camera in an extremely cluttered space. Lowering the confidence threshold did not help by the way. I appreciate your help!

**Comment by jakob-ropers-snkeos** [comment]
Sure! Here are two example images and the CAD model of the needle holder:

https://drive.google.com/drive/folders/1pn7letIZNACC7D1u-pwCyPvzlMBdfHJ3?usp=drive_link

**Comment by nv-nguyen** [comment]
I added [stability_score_thresh](https://github.com/nv-nguyen/cnos/blob/main/src/scripts/inference_custom.py#L157) parameter in [inference_custom.py](https://github.com/nv-nguyen/cnos/blob/main/src/scripts/inference_custom.py) script so that the segmentation model can output more unstable masks (usually happens for very tiny objects like yours). Here is the result after fine-tuning this parameter of SAM:

![result](https://github.com/nv-nguyen/cnos/assets/54082176/8feaadb4-23f8-4b1b-9eca-335be931fb77)

 Here are the command to reproduce the results:

```
export CAD_PATH=./media/demo2/NeedleHolder.ply
export RGB_PATH=./media/demo2/ThreeToolTest.png
export OUTPUT_DIR=./tmp/custom_dataset
python -m src.scripts.inference_custom --template_dir $OUTPUT_DIR --rgb_path $RGB_PATH --stability_score_thresh 0.5
```

I shared your example in this repo so that new users can be aware of it. Please let me know if you don't want to share this example. Thanks!

**Comment by jakob-ropers-snkeos** [comment]
Thank you so much for he very quick response and great solution! Yes I am okay with this being used as an example!

**Comment by jakob-ropers-snkeos** [comment]
I can confirm that this change makes it work perfectly on all my tools, not just the needle holder!

**Comment by JZhao12** [comment]
Hi jakob, I'm struggling in building CAD models for objects like yours. May I ask how you build the models of these small medical objects? 

![Image](https://github.com/user-attachments/assets/f452bddb-d872-4e3c-9526-0f4684ab6128)
